osx_image: xcode8.3
language: javascript
sudo: required
dist: trusty
matrix:
  include:
  - os: osx
  - os: linux
    env: CC=clang CXX=clang++ npm_config_clang=1
    compiler: clang
cache:
  directories:
  - node_modules
  - app/node_modules
  - "$HOME/.electron"
  - "$HOME/.cache"
addons:
  apt:
    packages:
    - libgnome-keyring-dev
    - icnsutils
before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install --no-install-recommends -y icnsutils graphicsmagick xz-utils; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then https://dl.winehq.org/wine-builds/Release.key; sudo apt-get update; sudo apt-get install wine; fi
install:
- nvm install 6
- npm run installdeps
- npm run pre-build
- npm prune
script:
- ./build_travis.sh